import { createContext, useContext, useState, type ReactNode } from 'react'

type Language = 'zh' | 'en'

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar
    'nav.home': '首页',
    'nav.map': '互动地图',
    'nav.compare': '建筑对比',
    'nav.ai': 'AI咨询',
    'nav.data': '数据中心',
    'nav.archive': '文献档案',
    'nav.about': '关于',
    
    // Home
    'home.hero.title': '中国古建筑的智慧',
    'home.hero.subtitle': '探索 15 种传统中国建筑如何适应不同气候环境',
    'home.hero.cta': '探索平台',
    'home.hero.interior': '窑洞室内',
    'home.hero.interior.desc': '夏季恒温舒适',
    'home.hero.exterior': '室外沙漠',
    'home.hero.exterior.desc': '极端高温环境',
    'home.buildings.title': '15 种传统建筑类型',
    'home.buildings.subtitle': '点击了解每种建筑的气候适应策略',
    'home.buildings.developing': '新增 10 种古建筑类型已上线。',
    'home.features.title': '平台核心功能',
    'home.features.exploration': '互动探索',
    'home.features.exploration.desc': '通过交互式地图探索不同地区的气候特征与建筑适应策略',
    'home.features.ai': 'AI 气候顾问',
    'home.features.ai.desc': '智能推荐适合特定气候条件的传统建筑策略',
    'home.features.data': '数据可视化',
    'home.features.data.desc': '对比分析不同建筑类型的气候适应性能',
    'home.cta.title': '开始探索古代建筑智慧',
    'home.cta.subtitle': '了解传统建筑如何在没有现代技术的情况下实现可持续设计',
    'home.cta.map': '浏览互动地图',
    'home.cta.compare': '对比建筑类型',
    
    // Map
    'map.controls': '地图控制与筛选',
    'map.temperature': '温度',
    'map.humidity': '湿度',
    'map.precipitation': '降水量',
    'map.zoomIn': '放大 +',
    'map.zoomOut': '缩小 -',
    'map.title': '互动中国地图 - 3D全息视图',
    'map.legend': '图例',
    'map.hot': '炎热气候',
    'map.cold': '寒冷气候',
    'map.humid': '潮湿气候',
    'map.location': '地区',
    'map.climate': '气候',
    'map.viewDetails': '查看详情 →',
    'map.allBuildings': '所有建筑类型',
    
    // Comparison
    'compare.title': '建筑对比分析',
    'compare.select': '选择对比建筑',
    'compare.buildingA': '建筑 A:',
    'compare.buildingB': '建筑 B:',
    'compare.3dModels': '3D 模型对比',
    'compare.interactive': '[交互式 3D 模型]',
    'compare.controls': '旋转 • 缩放 • 剖面视图',
    'compare.region': '地区',
    'compare.climate': '气候',
    'compare.performance': '性能对比',
    'compare.features': '特征对比表',
    'compare.feature': '特征',
    'compare.wallThickness': '墙体厚度',
    'compare.circularLayout': '圆形布局',
    'compare.courtyardDesign': '庭院设计',
    'compare.naturalVentilation': '自然通风',
    'compare.floodDesign': '防洪设计',
    'compare.tempRegulation': '温度调节',
    'compare.humidityControl': '湿度控制',
    'compare.energyEfficiency': '能源效率',
    
    // Building Climate
    'detail.climate.tulou': '高湿度、台风',
    'detail.climate.siheyuan': '夏热冬冷',
    'detail.climate.yaodong': '极端温差',
    'detail.climate.diaojiaolou': '山地潮湿、洪涝',
    'detail.climate.weilongwu': '亚热带炎热',
    
    // Building Detail
    'detail.crossSection': '动画剖面查看器',
    'detail.airflow': '气流',
    'detail.thermal': '热量',
    'detail.moisture': '湿度',
    'detail.structure': '结构',
    'detail.climatePanel': '气候数据面板',
    'detail.tempRange': '温度范围',
    'detail.humidity': '湿度',
    'detail.precipitation': '年降水量',
    'detail.adaptations': '关键气候适应策略',
    'detail.timeline': '历史演变时间线',
    'detail.gallery': '图片画廊',
    'detail.song': '宋代',
    'detail.ming': '明代',
    'detail.qing': '清代',
    'detail.modern': '现代',
    'detail.evolutionDesc': '演变说明',
    'detail.region': '地区',
    
    // AI Consultant
    'ai.title': 'AI 气候顾问',
    'ai.quickPrompts': '快速提问',
    'ai.chat': '对话界面',
    'ai.placeholder': '询问气候适应策略...',
    'ai.photoAnalysis': '图片分析',
    'ai.upload': '上传照片',
    'ai.dragDrop': '拖放或点击选择',
    'ai.detect': 'AI 将检测:',
    'ai.buildingType': '建筑类型',
    'ai.features': '气候适应特征',
    'ai.materials': '材料组成',
    'ai.ventilation': '通风系统',
    'ai.exampleResult': '示例 AI 分析结果',
    'ai.detectionResult': '检测结果:',
    'ai.confidence': '置信度',
    'ai.detectedFeatures': '检测到的特征',
    'ai.uploadedImage': '[上传的建筑图片 + AI 标注]',
    'ai.imageWithAnnotations': '带有 AI 注释的上传图片',
    'ai.tulouConfidence': '福建土楼 (Tulou) - 95% 置信度',
    'ai.circularStructure': '圆形夯土结构',
    'ai.thickWalls': '厚实防御墙体',
    'ai.centralCourtyard': '中央庭院',
    'ai.relatedBuilding': '相关建筑',
    
    // Data Hub
    'data.title': '数据中心',
    'data.filters': '数据筛选与控制',
    'data.timePeriod': '时间段',
    'data.allPeriods': '所有时期',
    'data.ancient': '古代 (1900年前)',
    'data.modern': '现代 (1900年至今)',
    'data.buildingType': '建筑类型',
    'data.allTypes': '所有类型',
    'data.climateVar': '气候变量',
    'data.apply': '应用筛选',
    'data.timeline': '演变时间线 - 交互式 3D',
    'data.performance': '对比性能图表',
    'data.tempEfficiency': '温度调节效率',
    'data.correlation': '气候-建筑关联图',
    'data.seasonal': '季节性能对比',
    'data.spring': '春季',
    'data.summer': '夏季',
    'data.autumn': '秋季',
    'data.winter': '冬季',
    'data.export': '导出与下载',
    'data.downloadPDF': '下载报告 (PDF)',
    'data.exportCSV': '导出数据 (CSV)',
    'data.savePNG': '保存可视化 (PNG)',
    
    // Archive
    'archive.title': '文献档案',
    'archive.search': '搜索与筛选',
    'archive.searchPlaceholder': '搜索文献、关键词...',
    'archive.allDynasties': '所有朝代',
    'archive.library': '文献库',
    'archive.viewer': '文献查看器 - 双语对照',
    'archive.original': '原文 (古文)',
    'archive.translation': 'AI 现代翻译',
    'archive.wisdom': '精选智慧段落',
    'archive.source': '来源',
    'archive.pages': '页',
    'archive.zoomIn': '放大',
    'archive.zoomOut': '缩小',
    'archive.extractedWisdom': '提取的建筑智慧:',
    'archive.siteSelection': '基于地形选址',
    'archive.soilAssessment': '土壤质量评估至关重要',
    'archive.platformConstruction': '潮湿地区采用平台建造',
    'archive.doc1': '营造法式',
    'archive.doc2': '工部工程做法',
    'archive.doc3': '闽南建筑志',
    'archive.doc4': '北方居住建筑',
    'archive.ventilationDesign': '通风设计',
    'archive.thermalMass': '热质量',
    'archive.waterManagement': '水管理',
    'archive.materialSelection': '材料选择',
    'archive.ventilationText': '窗户的战略布置实现交叉通风...',
    'archive.thermalText': '厚墙在夏季储存凉爽，冬季储存温暖...',
    'archive.waterText': '屋顶排水系统防止湿气损害...',
    'archive.materialText': '当地材料适应区域气候...',
    'archive.translationP1': '建造宫殿和建筑时，必须首先勘察地形的高低和土壤的坚硬程度，以确定基础位置。',
    'archive.translationP2': '如果地势低洼潮湿，应建造平台以抬高基础...',
    
    // About
    'about.hero': '从古至今的转变',
    'about.traditional': '传统建筑',
    'about.ancientWisdom': '古代气候智慧',
    'about.modernGreen': '现代绿色建筑',
    'about.sustainable': '可持续未来',
    'about.overview': '项目概述',
    'about.mission': '使命宣言',
    'about.missionText': '筑智千年通过 AI 驱动的分析和交互式可视化，将古代气候响应式设计智慧与当代可持续建筑需求相连接。',
    'about.buildingTypes': '建筑类型',
    'about.yearsWisdom': '年智慧积累',
    'about.aiPowered': '驱动分析',
    'about.methodology': '方法论 - 三步流程',
    'about.dataCollection': '数据收集',
    'about.dataCollectionDesc': '气候数据、建筑调查、历史文献',
    'about.aiAnalysis': 'AI 分析',
    'about.aiAnalysisDesc': '模式识别、文本挖掘、特征检测',
    'about.visualization': '可视化',
    'about.visualizationDesc': '交互式 3D 模型、对比图表、洞察',
    'about.team': '团队',
    'about.dataSources': '数据来源与合作伙伴',
    'about.applications': '现代应用',
    'about.greenBuilding': '绿色建筑设计',
    'about.education': '教育与研究',
    'about.contact': '联系与资源',
    'about.contactUs': '联系我们',
    'about.name': '姓名',
    'about.email': '邮箱',
    'about.message': '留言',
    'about.send': '发送消息',
    'about.resources': '下载资源',
    
    // Building Adaptations
    'adapt.tulou.1': '厚实的夯土墙（1-2米）提供热质量',
    'adapt.tulou.2': '圆形布局促进自然空气流通',
    'adapt.tulou.3': '小型外部开口减少热交换',
    'adapt.tulou.4': '多层设计最大化内部空间',
    'adapt.siheyuan.1': '庭院微气候调节温度',
    'adapt.siheyuan.2': '南向布局最大化冬季日照',
    'adapt.siheyuan.3': '厚墙体提供保温隔热',
    'adapt.siheyuan.4': '檐廊设计遮阳避雨',
    'adapt.yaodong.1': '地下建造利用土层热质量',
    'adapt.yaodong.2': '恒温效果（冬暖夏凉）',
    'adapt.yaodong.3': '最小化暴露表面积',
    'adapt.yaodong.4': '就地取材节省资源',
    'adapt.diaojiaolou.1': '架空结构防洪防潮',
    'adapt.diaojiaolou.2': '底层通风除湿',
    'adapt.diaojiaolou.3': '木结构适应山地地形',
    'adapt.diaojiaolou.4': '坡屋顶快速排水',
    'adapt.weilongwu.1': '半圆形围合布局聚气',
    'adapt.weilongwu.2': '水塘调节微气候',
    'adapt.weilongwu.3': '厚墙体隔热',
    'adapt.weilongwu.4': '天井通风采光',
    
    // Buildings
    'building.tulou': '福建土楼',
    'building.siheyuan': '北京四合院',
    'building.yaodong': '陕北窑洞',
    'building.diaojiaolou': '西南吊脚楼',
    'building.weilongwu': '客家围龙屋',
    'building.fujian': '福建',
    'building.northChina': '华北',
    'building.loessPlateau': '黄土高原',
    'building.yunguizhou': '云贵',
    'building.guangdong': '广东',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.map': 'Map',
    'nav.compare': 'Compare',
    'nav.ai': 'AI Consultant',
    'nav.data': 'Data Hub',
    'nav.archive': 'Archive',
    'nav.about': 'About',
    
    // Home
    'home.hero.title': 'The Wisdom of Ancient Chinese Architecture',
    'home.hero.subtitle': 'Explore how 15 traditional Chinese building types adapt to different climates',
    'home.hero.cta': 'Explore Platform',
    'home.hero.interior': 'Yaodong Interior',
    'home.hero.interior.desc': 'Cool and comfortable in summer',
    'home.hero.exterior': 'Desert Exterior',
    'home.hero.exterior.desc': 'Extreme heat environment',
    'home.buildings.title': '15 Traditional Building Types',
    'home.buildings.subtitle': 'Click to learn about each building\'s climate adaptation strategies',
    'home.buildings.developing': '10 newly added traditional building types are now available.',
    'home.features.title': 'Platform Core Features',
    'home.features.exploration': 'Interactive Exploration',
    'home.features.exploration.desc': 'Explore climate characteristics and architectural adaptations through interactive maps',
    'home.features.ai': 'AI Climate Consultant',
    'home.features.ai.desc': 'Smart recommendations for traditional building strategies suited to specific climates',
    'home.features.data': 'Data Visualization',
    'home.features.data.desc': 'Compare and analyze climate adaptation performance across building types',
    'home.cta.title': 'Start Exploring Ancient Architectural Wisdom',
    'home.cta.subtitle': 'Learn how traditional buildings achieved sustainable design without modern technology',
    'home.cta.map': 'Browse Interactive Map',
    'home.cta.compare': 'Compare Building Types',
    
    // Map
    'map.controls': 'Map Controls & Filters',
    'map.temperature': 'Temperature',
    'map.humidity': 'Humidity',
    'map.precipitation': 'Precipitation',
    'map.zoomIn': 'Zoom +',
    'map.zoomOut': 'Zoom -',
    'map.title': 'Interactive China Map - 3D Holographic View',
    'map.legend': 'Legend',
    'map.hot': 'Hot Climate',
    'map.cold': 'Cold Climate',
    'map.humid': 'Humid Climate',
    'map.location': 'Location',
    'map.climate': 'Climate',
    'map.viewDetails': 'View Details →',
    'map.allBuildings': 'All Building Types',
    
    // Comparison
    'compare.title': 'Building Comparison Analysis',
    'compare.select': 'Select Buildings to Compare',
    'compare.buildingA': 'Building A:',
    'compare.buildingB': 'Building B:',
    'compare.3dModels': '3D Model Comparison',
    'compare.interactive': '[Interactive 3D Model]',
    'compare.controls': 'Rotate • Zoom • Cutaway View',
    'compare.region': 'Region',
    'compare.climate': 'Climate',
    'compare.performance': 'Performance Comparison',
    'compare.features': 'Feature Comparison Table',
    'compare.feature': 'Feature',
    'compare.wallThickness': 'Wall Thickness',
    'compare.circularLayout': 'Circular Layout',
    'compare.courtyardDesign': 'Courtyard Design',
    'compare.naturalVentilation': 'Natural Ventilation',
    'compare.floodDesign': 'Flood Protection',
    'compare.tempRegulation': 'Temperature Regulation',
    'compare.humidityControl': 'Humidity Control',
    'compare.energyEfficiency': 'Energy Efficiency',
    
    // Building Climate
    'detail.climate.tulou': 'High humidity, typhoons',
    'detail.climate.siheyuan': 'Hot summers, cold winters',
    'detail.climate.yaodong': 'Extreme temperature swings',
    'detail.climate.diaojiaolou': 'Mountain moisture, floods',
    'detail.climate.weilongwu': 'Subtropical heat',
    
    // Building Detail
    'detail.crossSection': 'Animated Cross-Section Viewer',
    'detail.airflow': 'Airflow',
    'detail.thermal': 'Thermal',
    'detail.moisture': 'Moisture',
    'detail.structure': 'Structure',
    'detail.climatePanel': 'Climate Data Panel',
    'detail.tempRange': 'Temperature Range',
    'detail.humidity': 'Humidity',
    'detail.precipitation': 'Annual Precipitation',
    'detail.adaptations': 'Key Climate Adaptations',
    'detail.timeline': 'Historical Evolution Timeline',
    'detail.gallery': 'Photo Gallery',
    'detail.song': 'Song Dynasty',
    'detail.ming': 'Ming Dynasty',
    'detail.qing': 'Qing Dynasty',
    'detail.modern': 'Modern',
    'detail.evolutionDesc': 'Evolution description',
    'detail.region': 'Region',
    
    // AI Consultant
    'ai.title': 'AI Climate Consultant',
    'ai.quickPrompts': 'Quick Prompts',
    'ai.chat': 'Chat Interface',
    'ai.placeholder': 'Ask about climate strategies...',
    'ai.photoAnalysis': 'Photo Analysis',
    'ai.upload': 'Upload Photo',
    'ai.dragDrop': 'Drag & drop or click',
    'ai.detect': 'AI will detect:',
    'ai.buildingType': 'Building type',
    'ai.features': 'Climate-adaptive features',
    'ai.materials': 'Material composition',
    'ai.ventilation': 'Ventilation systems',
    'ai.exampleResult': 'Example AI Analysis Result',
    'ai.detectionResult': 'Detection Results:',
    'ai.confidence': 'confidence',
    'ai.detectedFeatures': 'Detected Features',
    'ai.uploadedImage': '[Uploaded building image + AI annotations]',
    'ai.imageWithAnnotations': 'Uploaded image with AI annotations',
    'ai.tulouConfidence': 'Fujian Tulou - 95% confidence',
    'ai.circularStructure': 'Circular rammed earth structure',
    'ai.thickWalls': 'Thick defensive walls',
    'ai.centralCourtyard': 'Central courtyard',
    'ai.relatedBuilding': 'Related Building',
    
    // Data Hub
    'data.title': 'Data Hub',
    'data.filters': 'Data Filters & Controls',
    'data.timePeriod': 'Time Period',
    'data.allPeriods': 'All Periods',
    'data.ancient': 'Ancient (Before 1900)',
    'data.modern': 'Modern (1900-Present)',
    'data.buildingType': 'Building Type',
    'data.allTypes': 'All Types',
    'data.climateVar': 'Climate Variable',
    'data.apply': 'Apply Filters',
    'data.timeline': 'Evolution Timeline - Interactive 3D',
    'data.performance': 'Comparative Performance Chart',
    'data.tempEfficiency': 'Temperature Regulation Efficiency',
    'data.correlation': 'Climate-Architecture Correlation',
    'data.seasonal': 'Seasonal Performance Comparison',
    'data.spring': 'Spring',
    'data.summer': 'Summer',
    'data.autumn': 'Autumn',
    'data.winter': 'Winter',
    'data.export': 'Export & Download',
    'data.downloadPDF': 'Download Report (PDF)',
    'data.exportCSV': 'Export Data (CSV)',
    'data.savePNG': 'Save Visualizations (PNG)',
    
    // Archive
    'archive.title': 'Text Archive',
    'archive.search': 'Search & Filter',
    'archive.searchPlaceholder': 'Search texts, keywords...',
    'archive.allDynasties': 'All Dynasties',
    'archive.library': 'Document Library',
    'archive.viewer': 'Document Viewer - Side-by-side Translation',
    'archive.original': 'Original Text (Classical Chinese)',
    'archive.translation': 'AI Modern Translation',
    'archive.wisdom': 'Highlighted Wisdom Passages',
    'archive.source': 'Source',
    'archive.pages': 'pages',
    'archive.zoomIn': 'Zoom In',
    'archive.zoomOut': 'Zoom Out',
    'archive.extractedWisdom': 'Extracted Architectural Wisdom:',
    'archive.siteSelection': 'Site selection based on terrain',
    'archive.soilAssessment': 'Soil quality assessment is crucial',
    'archive.platformConstruction': 'Platform construction for damp areas',
    'archive.doc1': 'Yingzao Fashi',
    'archive.doc2': 'Gongbu Gongcheng Zuofa',
    'archive.doc3': 'Minnan Architecture Records',
    'archive.doc4': 'Northern Residential Buildings',
    'archive.ventilationDesign': 'Ventilation Design',
    'archive.thermalMass': 'Thermal Mass',
    'archive.waterManagement': 'Water Management',
    'archive.materialSelection': 'Material Selection',
    'archive.ventilationText': 'Strategic window placement enables cross-ventilation...',
    'archive.thermalText': 'Thick walls store coolness in summer, warmth in winter...',
    'archive.waterText': 'Roof drainage systems prevent moisture damage...',
    'archive.materialText': 'Local materials adapt to regional climate...',
    'archive.translationP1': 'When constructing palaces and buildings, one must first survey the terrain elevation and soil hardness to determine the foundation location.',
    'archive.translationP2': 'If the terrain is low and damp, a platform should be built to raise the foundation...',
    
    // About
    'about.hero': 'Ancient to Modern Transformation',
    'about.traditional': 'Traditional Architecture',
    'about.ancientWisdom': 'Ancient Climate Wisdom',
    'about.modernGreen': 'Modern Green Building',
    'about.sustainable': 'Sustainable Future',
    'about.overview': 'Project Overview',
    'about.mission': 'Mission Statement',
    'about.missionText': 'Five Dimensions of Chinese Architecture bridges ancient climate-responsive design wisdom with contemporary sustainable architecture needs through AI-powered analysis and interactive visualization.',
    'about.buildingTypes': 'Building Types',
    'about.yearsWisdom': 'Years of Wisdom',
    'about.aiPowered': 'Powered Analysis',
    'about.methodology': 'Methodology - 3-Step Process',
    'about.dataCollection': 'Data Collection',
    'about.dataCollectionDesc': 'Climate data, architectural surveys, historical texts',
    'about.aiAnalysis': 'AI Analysis',
    'about.aiAnalysisDesc': 'Pattern recognition, text mining, feature detection',
    'about.visualization': 'Visualization',
    'about.visualizationDesc': 'Interactive 3D models, comparative charts, insights',
    'about.team': 'Team',
    'about.dataSources': 'Data Sources & Partners',
    'about.applications': 'Modern Applications',
    'about.greenBuilding': 'Green Building Design',
    'about.education': 'Education & Research',
    'about.contact': 'Contact & Resources',
    'about.contactUs': 'Contact Us',
    'about.name': 'Name',
    'about.email': 'Email',
    'about.message': 'Message',
    'about.send': 'Send Message',
    'about.resources': 'Download Resources',
    
    // Building Adaptations
    'adapt.tulou.1': 'Thick rammed earth walls (1-2m) provide thermal mass',
    'adapt.tulou.2': 'Circular layout promotes natural air circulation',
    'adapt.tulou.3': 'Small external openings reduce heat exchange',
    'adapt.tulou.4': 'Multi-story design maximizes interior space',
    'adapt.siheyuan.1': 'Courtyard microclimate regulates temperature',
    'adapt.siheyuan.2': 'South-facing layout maximizes winter sunlight',
    'adapt.siheyuan.3': 'Thick walls provide insulation',
    'adapt.siheyuan.4': 'Covered corridors provide shade and rain protection',
    'adapt.yaodong.1': 'Underground construction utilizes earth thermal mass',
    'adapt.yaodong.2': 'Constant temperature effect (warm in winter, cool in summer)',
    'adapt.yaodong.3': 'Minimized exposed surface area',
    'adapt.yaodong.4': 'Local materials save resources',
    'adapt.diaojiaolou.1': 'Elevated structure prevents flooding and moisture',
    'adapt.diaojiaolou.2': 'Ground-level ventilation removes humidity',
    'adapt.diaojiaolou.3': 'Wood structure adapts to mountain terrain',
    'adapt.diaojiaolou.4': 'Sloped roof enables rapid drainage',
    'adapt.weilongwu.1': 'Semi-circular enclosure layout gathers qi',
    'adapt.weilongwu.2': 'Pond regulates microclimate',
    'adapt.weilongwu.3': 'Thick walls provide insulation',
    'adapt.weilongwu.4': 'Skywell provides ventilation and lighting',
    
    // Buildings
    'building.tulou': 'Fujian Tulou',
    'building.siheyuan': 'Beijing Siheyuan',
    'building.yaodong': 'Shaanbei Yaodong',
    'building.diaojiaolou': 'Diaojiaolou',
    'building.weilongwu': 'Hakka Weilongwu',
    'building.fujian': 'Fujian',
    'building.northChina': 'North China',
    'building.loessPlateau': 'Loess Plateau',
    'building.yunguizhou': 'Yunnan/Guizhou',
    'building.guangdong': 'Guangdong',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>('zh')

  const t = (key: string): string => {
    return translations[lang][key] || key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
